### PR TITLE
Single-threading

### PR DESCRIPTION
**Pull request by SquidDev**
`yield` and `resume` throw a `UnwindThrowable` which unwinds the entire stack. `LuaThread.run` handles swapping between the various coroutines, negotiating resumes and yields.

## Initial requirements
 - Add support for:
   - [x] `string.gsub`
   - [x] `table.sort`
   - [x] Concatenation
 - [x] Yielding tailcalls
 - [x] Prohibit yielding in some places (debug hooks, `load` from a function)
 - [ ] Allow resuming child coroutines where yielding is prohibited.
 - [x] Get all tests passing
 - [ ] Throwing errors in weird places - debug hooks (especially return, etc...). Verify the stack is maintained and whatnot.

## Possible extensions
 - [x] Yielding within debug hooks
 - ~~Yielding within `DebugHandler.poll`.~~ Nah.

## Before merge
Validate yielding works in the above and
 - [x] Metamethods
 - [x] Concat metamethod
 - [x] `__index` and `__newindex`.
 - [x] `pcall` and `xpcall` (including error handler).
 - [x] Sorting via compare function
 - [x] Sorting via metamethod

### CODE REVIEW

**Comment by timofonic** [comment]
@SquidDev Any hopes to have this finished? :D

**Comment by SquidDev** [comment]
@timofonic I'm hoping to finish it at some point. Adding support for yielding in debug hooks proved harder than expected, delaying development of this. Additionally, the person who initially asked about single threading Cobalt no longer has a need, and so I've not really had a need to look at it since.

**Comment by SquidDev** [comment]
I like how I tested this locally and it worked fine. Yay.

**Comment by SquidDev** [comment]
Some numbers:

### fdcec19 (master) Add a more general way of running functions on the main coroutine
```
Benchmark                          Mode  Cnt   Score   Error  Units
PerformanceBenchmark.binarytrees  thrpt   15   7.879 ± 0.141  ops/s
PerformanceBenchmark.fannkuch     thrpt   15  12.318 ± 0.738  ops/s
PerformanceBenchmark.nbody        thrpt   15   1.537 ± 0.051  ops/s
PerformanceBenchmark.nsieve       thrpt   15   0.608 ± 0.009  ops/s
```

### 57e6604 Run all coroutines on a single thread
```
Benchmark                          Mode  Cnt   Score   Error  Units
PerformanceBenchmark.binarytrees  thrpt   15   7.405 ± 0.131  ops/s
PerformanceBenchmark.fannkuch     thrpt   15  12.197 ± 0.440  ops/s
PerformanceBenchmark.nbody        thrpt   15   1.357 ± 0.019  ops/s
PerformanceBenchmark.nsieve       thrpt   15   0.548 ± 0.016  ops/s
```

### e4200b5 Fix returning to outselves when calling yieldBlocking
```
Benchmark                          Mode  Cnt   Score   Error  Units
PerformanceBenchmark.binarytrees  thrpt   15   7.367 ± 0.138  ops/s
PerformanceBenchmark.fannkuch     thrpt   15  11.903 ± 0.130  ops/s
PerformanceBenchmark.nbody        thrpt   15   1.369 ± 0.032  ops/s
PerformanceBenchmark.nsieve       thrpt   15   0.575 ± 0.027  ops/s
```

As we can see, performance is substantially worse compared with master (though these are pretty high error margins). I'd really like to get this down to something sane (7.6 for binarytrees for instance), though I can't promise anything.

**Pull request merged**
