### PR TITLE
Support __len in #x when x is a table

### PR DESCRIPTION
**Pull request by plt-abigail**
One step closer to Lua 5.2 support.

### CODE REVIEW

**Comment by plt-abigail** [comment]
Also sorry I'm not writing tests. I don't understand your test sutie

**Comment by SquidDev** [comment]
I wonder if it's also worth adding support for `rawlen` here too?

**Comment by plt-abigail** [comment]
I didn't even know `rawlen` was a thing. On it :+1:

**Comment by SquidDev** [comment]
Thank you very much!

**Pull request merged**
